# Site settings
title: Tully Hansen
email: tully@tullyhansen.com.com
description: > # this means to ignore newlines until "baseurl:"
  Updating my homepage since 1998.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tullyhansen.com" # the base hostname & protocol for your site
twitter_username: tullyhansen
github_username:  tullyhansen

# Build settings
markdown: kramdown
